SELECT * FROM DBA_USERS;

CREATE USER TEST01 IDENTIFIED BY 1234;
GRANT RESOURCE, DBA, CONNECT TO TEST01;

CREATE USER TEST02 IDENTIFIED BY 1234;

GRANT RESOURCE, DBA, CONNECT TO TEST02;


CREATE USER TEST03 IDENTIFIED BY 1234;

GRANT RESOURCE, DBA, CONNECT TO TEST03;


CREATE TABLE TEST01.TBL_LT_INF
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    FL_ID   VARCHAR2(50),
    OP_ID   VARCHAR2(50),
    TIMEKEY VARCHAR2(50),
    CHG_TM  VARCHAR2(50),
    CRT_TM  VARCHAR2(50)  
);

CREATE UNIQUE INDEX TEST01.TBL_LT_INF_PK ON TEST01.TBL_LT_INF (FA_ID, LT_ID, PROD_ID);

ALTER TABLE TEST01.TBL_LT_INF ADD CONSTRAINT  TBL_LT_INF_PK PRIMARY KEY (FA_ID, LT_ID, PROD_ID);


CREATE TABLE TEST01.TBL_LT_DET
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    PROD_DESC   VARCHAR2(2000),
    FL_ID   VARCHAR2(50),
    FL_DESC     VARCHAR2(2000),
    OP_ID   VARCHAR2(50),
    OP_DESC VARCHAR2(2000),
    EVENT_DESC  VARCHAR2(2000),
    USER_ID VARCHAR2(50)
    
);

CREATE UNIQUE INDEX TEST01.TBL_LT_DET_PK ON TEST01.TBL_LT_DET(FA_ID, LT_ID, PROD_ID);

ALTER TABLE TEST01.TBL_LT_DET ADD CONSTRAINT TBL_LT_DET_PK PRIMARY KEY(FA_ID, LT_ID, PROD_ID);

CREATE TABLE TEST01.TBL_LT_HIS
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    TIMEKEY VARCHAR2(50),
    FL_ID   VARCHAR2(50),
    OP_ID   VARCHAR2(50),
    STAT_CD VARCHAR2(40),
    STAT_TYP    VARCHAR2(50)

);

CREATE UNIQUE INDEX TEST01.TBL_LT_HIS_PK ON TEST01.TBL_LT_HIS(FA_ID, LT_ID, PROD_ID, TIMEKEY);

ALTER TABLE TEST01.TBL_LT_HIS ADD CONSTRAINT TBL_LT_HIS_PK PRIMARY KEY(FA_ID, LT_ID, PROD_ID, TIMEKEY);

INSERT INTO TEST01.TBL_LT_INF
    SELECT 'F11', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 )
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 10000
    
    ;


INSERT INTO TEST01.TBL_LT_INF
    SELECT 'F12', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 )
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 20000
    
    ;
INSERT INTO TEST01.TBL_LT_INF
    SELECT 'F13', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 )
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 3000
    
    ;
    
INSERT INTO TEST01.TBL_LT_INF
    SELECT 'F14', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TO_cHAR(TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 ))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 5000
    
    ;


INSERT INTO TEST01.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190803' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'SHIP'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST01.TBL_LT_INF
 
    ;

INSERT INTO TEST01.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190801' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'RELE'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST01.TBL_LT_INF
 
    ;

INSERT INTO TEST01.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190802' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'SCRP'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST01.TBL_LT_INF
 
    ;
    
INSERT INTO TEST01.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190813' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'EMPTY'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST01.TBL_LT_INF
 
    ;
    

INSERT INTO TEST01.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190823' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'SHIP'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST01.TBL_LT_INF
 
    ;

INSERT INTO TEST01.TBL_LT_DET
SELECT FA_ID, LT_ID, PROD_ID, DBMS_RANDOM.STRING('X', 10), FL_ID, DBMS_RANDOM.STRING('X', 10), OP_ID, DBMS_RANDOM.STRING('X', 10),
DBMS_RANDOM.STRING('X', 10), 'KMG28801'
FROM TEST01.TBL_LT_INF
;

COMMIT;






CREATE TABLE TEST02.TBL_LT_INF
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    FL_ID   VARCHAR2(50),
    OP_ID   VARCHAR2(50),
    TIMEKEY VARCHAR2(50),
    CHG_TM  VARCHAR2(50),
    CRT_TM  VARCHAR2(50)  
);

CREATE UNIQUE INDEX TEST02.TBL_LT_INF_PK ON TEST02.TBL_LT_INF (FA_ID, LT_ID, PROD_ID);

ALTER TABLE TEST02.TBL_LT_INF ADD CONSTRAINT TBL_LT_INF_PK PRIMARY KEY (FA_ID, LT_ID, PROD_ID);


CREATE TABLE TEST02.TBL_LT_DET
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    PROD_DESC   VARCHAR2(2000),
    FL_ID   VARCHAR2(50),
    FL_DESC     VARCHAR2(2000),
    OP_ID   VARCHAR2(50),
    OP_DESC VARCHAR2(2000),
    EVENT_DESC  VARCHAR2(2000),
    USER_ID VARCHAR2(50)
    
);

CREATE UNIQUE INDEX TEST02.TBL_LT_DET_PK ON TEST02.TBL_LT_DET(FA_ID, LT_ID, PROD_ID);

ALTER TABLE TEST02.TBL_LT_DET ADD CONSTRAINT TBL_LT_DET_PK PRIMARY KEY(FA_ID, LT_ID, PROD_ID);

CREATE TABLE TEST02.TBL_LT_HIS
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    TIMEKEY VARCHAR2(50),
    FL_ID   VARCHAR2(50),
    OP_ID   VARCHAR2(50),
    STAT_CD VARCHAR2(40),
    STAT_TYP    VARCHAR2(50)

);

CREATE UNIQUE INDEX TEST02.TBL_LT_HIS_PK ON TEST02.TBL_LT_HIS(FA_ID, LT_ID, PROD_ID, TIMEKEY);

ALTER TABLE TEST02.TBL_LT_HIS ADD CONSTRAINT TBL_LT_HIS_PK PRIMARY KEY(FA_ID, LT_ID, PROD_ID, TIMEKEY);

INSERT INTO TEST02.TBL_LT_INF
SELECT *
  FROM TEST01.TBL_LT_INF
 WHERE ROWNUM <= 1000
 ;



INSERT INTO TEST02.TBL_LT_DET
SELECT *
  FROM TEST01.TBL_LT_DET
 WHERE ROWNUM <= 1000
 ;
 
INSERT INTO TEST02.TBL_LT_HIS
SELECT *
  FROM TEST01.TBL_LT_HIS
 WHERE ROWNUM <= 1000
 ;


INSERT INTO TEST02.TBL_LT_INF
    SELECT 'F11', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 )
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 10000
    
    ;


INSERT INTO TEST02.TBL_LT_INF
    SELECT 'F12', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 )
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 20000
    
    ;
INSERT INTO TEST02.TBL_LT_INF
    SELECT 'F13', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 )
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 3000
    
    ;
    
INSERT INTO TEST02.TBL_LT_INF
    SELECT 'F14', DBMS_RANDOM.STRING('U', 3) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , DBMS_RANDOM.STRING('X', 10)
    , DBMS_RANDOM.STRING('X', 20)
    , DBMS_RANDOM.STRING('U', 2) || TRUNC(DBMS_RANDOM.VALUE(1000, 10000))
    , TO_cHAR(TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   100 ))
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   50 ) 
    , TRUNC( SYSDATE ) - 100 + CEIL( LEVEL/   200 ) COL1
    FROM DUAL
    CONNECT BY LEVEL <= 5000
    
    ;


INSERT INTO TEST02.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190803' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'SHIP'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST02.TBL_LT_INF
 
    ;

INSERT INTO TEST02.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190801' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'RELE'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST02.TBL_LT_INF
 
    ;

INSERT INTO TEST02.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190802' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'SCRP'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST02.TBL_LT_INF
 
    ;
    
INSERT INTO TEST02.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190813' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'EMPTY'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST02.TBL_LT_INF
 
    ;
    

INSERT INTO TEST02.TBL_LT_HIS
SELECT FA_ID, LT_ID, PROD_ID, '20190823' || DBMS_RANDOM.VALUE(1000, 10000)
    , FL_ID,  OP_ID, 'SHIP'
    , CASE WHEN MOD(ROWNUM, 4) = 1 THEN 'LOADING'
           WHEN MOD(ROWNUM, 4) = 2 THEN 'SELEECT'
           WHEN MOD(ROWNUM, 4) = 3 THEN 'PROCESS'
           ELSE 'RESERVE'
           END
    
    FROM TEST02.TBL_LT_INF
 
    ;

INSERT INTO TEST02.TBL_LT_DET
SELECT FA_ID, LT_ID, PROD_ID, DBMS_RANDOM.STRING('X', 10), FL_ID, DBMS_RANDOM.STRING('X', 10), OP_ID, DBMS_RANDOM.STRING('X', 10),
DBMS_RANDOM.STRING('X', 10), 'KMG28801'
FROM TEST02.TBL_LT_INF
;

COMMIT;






CREATE TABLE TEST03.TBL_LT_INF
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    FL_ID   VARCHAR2(50),
    OP_ID   VARCHAR2(50),
    TIMEKEY VARCHAR2(50),
    CHG_TM  VARCHAR2(50),
    CRT_TM  VARCHAR2(50)  
);

CREATE UNIQUE INDEX TEST03.TBL_LT_INF_PK ON TEST03.TBL_LT_INF (FA_ID, LT_ID, PROD_ID);

ALTER TABLE TEST03.TBL_LT_INF ADD CONSTRAINT TBL_LT_INF_PK PRIMARY KEY (FA_ID, LT_ID, PROD_ID);


CREATE TABLE TEST03.TBL_LT_DET
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    PROD_DESC   VARCHAR2(2000),
    FL_ID   VARCHAR2(50),
    FL_DESC     VARCHAR2(2000),
    OP_ID   VARCHAR2(50),
    OP_DESC VARCHAR2(2000),
    EVENT_DESC  VARCHAR2(2000),
    USER_ID VARCHAR2(50)
    
);

CREATE UNIQUE INDEX TEST03.TBL_LT_DET_PK ON TEST03.TBL_LT_DET(FA_ID, LT_ID, PROD_ID);

ALTER TABLE TEST03.TBL_LT_DET ADD CONSTRAINT TBL_LT_DET_PK PRIMARY KEY(FA_ID, LT_ID, PROD_ID);

CREATE TABLE TEST03.TBL_LT_HIS
(
    FA_ID   VARCHAR2(50),
    LT_ID   VARCHAR2(50),
    PROD_ID VARCHAR2(50),
    TIMEKEY VARCHAR2(50),
    FL_ID   VARCHAR2(50),
    OP_ID   VARCHAR2(50),
    STAT_CD VARCHAR2(40),
    STAT_TYP    VARCHAR2(50)

);

CREATE UNIQUE INDEX TEST03.TBL_LT_HIS_PK ON TEST03.TBL_LT_HIS(FA_ID, LT_ID, PROD_ID, TIMEKEY);

ALTER TABLE TEST03.TBL_LT_HIS ADD CONSTRAINT TBL_LT_HIS_PK PRIMARY KEY(FA_ID, LT_ID, PROD_ID, TIMEKEY);


