-- 1¹ø
INSERT INTO TEST03.TBL_LT_INF
	SELECT * FROM TEST01.TBL_LT_INF T1 WHERE NOT EXISTS (
		SELECT * FROM TEST02.TBL_LT_INF 
		WHERE (T1.FA_ID,T1.LT_ID,T1.PROD_ID)
		IN (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_INF))
	UNION ALL
	SELECT * FROM TEST02.TBL_LT_INF;

INSERT INTO TEST03.TBL_LT_DET
	SELECT * FROM TEST01.TBL_LT_DET T1 WHERE NOT EXISTS (
		SELECT * FROM TEST02.TBL_LT_DET 
		WHERE (T1.FA_ID,T1.LT_ID,T1.PROD_ID)
		IN (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_DET))
	UNION ALL
	SELECT * FROM TEST02.TBL_LT_DET;

INSERT INTO TEST03.TBL_LT_HIS
	SELECT * FROM TEST02.TBL_LT_HIS T2 WHERE NOT EXISTS (
		SELECT * FROM TEST01.TBL_LT_HIS 
		WHERE (T2.FA_ID,T2.LT_ID,T2.PROD_ID,T2.TIMEKEY)
		IN (SELECT FA_ID,LT_ID,PROD_ID,TIMEKEY FROM TEST01.TBL_LT_HIS))
	UNION ALL
	SELECT * FROM TEST01.TBL_LT_HIS;
    
-- 2¹ø

INSERT INTO TEST03.TBL_LT_INF
    SELECT * FROM TEST01.TBL_LT_INF T1
    WHERE FA_ID!='F12' AND
    NOT EXISTS (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_INF 
        WHERE (T1.FA_ID,T1.LT_ID,T1.PROD_ID) IN (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_INF))
    UNION ALL
    SELECT * FROM TEST02.TBL_LT_INF WHERE FA_ID!='F12';
    
MERGE INTO TEST03.TBL_LT_INF T3
    USING (SELECT 'F11',LT_ID,PROD_ID,FL_ID,OP_ID,TIMEKEY,CHG_TM,CRT_TM FROM TEST01.TBL_LT_INF T1
        WHERE FA_ID='F12' AND
        NOT EXISTS (SELECT 'F11',LT_ID,PROD_ID FROM TEST02.TBL_LT_INF 
            WHERE (T1.FA_ID,T1.LT_ID,T1.PROD_ID) IN (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_INF) AND FA_ID='F12')
        UNION ALL
        SELECT * FROM TEST02.TBL_LT_INF WHERE FA_ID='F12') T1T2
    ON (T3.FA_ID='F11' AND T3.LT_ID=T1T2.LT_ID AND T3.PROD_ID=T1T2.PROD_ID)
    WHEN NOT MATCHED THEN
        INSERT (T3.FA_ID,T3.LT_ID,T3.PROD_ID,T3.FL_ID,T3.OP_ID,T3.TIMEKEY,T3.CHG_TM,T3.CRT_TM) 
        VALUES ('F11',T1T2.LT_ID,T1T2.PROD_ID,T1T2.FL_ID,T1T2.OP_ID,T1T2.TIMEKEY,T1T2.CHG_TM,T1T2.CRT_TM);

INSERT INTO TEST03.TBL_LT_DET
    SELECT * FROM TEST01.TBL_LT_DET T1
    WHERE FA_ID!='F12' AND
    NOT EXISTS (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_DET 
        WHERE (T1.FA_ID,T1.LT_ID,T1.PROD_ID) IN (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_DET))
    UNION ALL
    SELECT * FROM TEST02.TBL_LT_DET WHERE FA_ID!='F12';
    
MERGE INTO TEST03.TBL_LT_DET T3
    USING (SELECT 'F11',LT_ID,PROD_ID,PROD_DESC,FL_ID,FL_DESC,OP_ID,OP_DESC,EVENT_DESC,USER_ID FROM TEST01.TBL_LT_DET T1
        WHERE FA_ID='F12' AND
        NOT EXISTS (SELECT 'F11',LT_ID,PROD_ID FROM TEST02.TBL_LT_DET 
            WHERE (T1.FA_ID,T1.LT_ID,T1.PROD_ID) IN (SELECT FA_ID,LT_ID,PROD_ID FROM TEST02.TBL_LT_DET) AND FA_ID='F12')
        UNION ALL
        SELECT * FROM TEST02.TBL_LT_DET WHERE FA_ID='F12') T1T2
    ON (T3.FA_ID='F11' AND T3.LT_ID=T1T2.LT_ID AND T3.PROD_ID=T1T2.PROD_ID)
    WHEN NOT MATCHED THEN
        INSERT (T3.FA_ID,T3.LT_ID,T3.PROD_ID,T3.PROD_DESC,T3.FL_ID,T3.FL_DESC,T3.OP_ID,T3.OP_DESC,T3.EVENT_DESC,T3.USER_ID) 
        VALUES ('F11',T1T2.LT_ID,T1T2.PROD_ID,T1T2.PROD_DESC,T1T2.FL_ID,T1T2.FL_DESC,T1T2.OP_ID,T1T2.OP_DESC,T1T2.EVENT_DESC,T1T2.USER_ID);

INSERT INTO TEST03.TBL_LT_HIS
    SELECT * FROM TEST02.TBL_LT_HIS T2
    WHERE FA_ID!='F12' AND
    NOT EXISTS (SELECT FA_ID,LT_ID,PROD_ID,TIMEKEY FROM TEST01.TBL_LT_HIS 
        WHERE (T2.FA_ID,T2.LT_ID,T2.PROD_ID,T2.TIMEKEY) IN (SELECT FA_ID,LT_ID,PROD_ID,TIMEKEY FROM TEST01.TBL_LT_HIS))
    UNION ALL
    SELECT * FROM TEST01.TBL_LT_HIS WHERE FA_ID!='F12';
    
MERGE INTO TEST03.TBL_LT_HIS T3
    USING (SELECT 'F11',LT_ID,PROD_ID,TIMEKEY,FL_ID,OP_ID,STAT_CD,STAT_TYP FROM TEST02.TBL_LT_HIS T2
        WHERE FA_ID='F12' AND
        NOT EXISTS (SELECT 'F11',LT_ID,PROD_ID,TIMEKEY FROM TEST01.TBL_LT_HIS 
            WHERE (T2.FA_ID,T2.LT_ID,T2.PROD_ID,T2.TIMEKEY) IN (SELECT FA_ID,LT_ID,PROD_ID,TIMEKEY FROM TEST01.TBL_LT_HIS) AND FA_ID='F12')
        UNION ALL
        SELECT * FROM TEST01.TBL_LT_HIS WHERE FA_ID='F12') T1T2
    ON (T3.FA_ID='F11' AND T3.LT_ID=T1T2.LT_ID AND T3.PROD_ID=T1T2.PROD_ID AND T3.TIMEKEY=T1T2.TIMEKEY)
    WHEN NOT MATCHED THEN
        INSERT (T3.FA_ID,T3.LT_ID,T3.PROD_ID,T3.TIMEKEY,T3.FL_ID,T3.OP_ID,T3.STAT_CD,T3.STAT_TYP) 
        VALUES ('F11',T1T2.LT_ID,T1T2.PROD_ID,T1T2.TIMEKEY,T1T2.FL_ID,T1T2.OP_ID,T1T2.STAT_CD,T1T2.STAT_TYP);
        
        
-- Feedback
INSERT INTO TEST03.TBL_LT_INF
SELECT CASE WHEN FA_ID = 'F12' THEN 'F11' ELSE FA_ID END AS FA_ID
     , LT_ID, PROD_ID, FL_ID, OP_ID, TIMEKEY, CHG_TM, CRT_TM
  FROM TEST01.TBL_LT_INF
 UNION ALL
SELECT CASE WHEN FA_ID = 'F12' THEN 'F11' ELSE FA_ID END AS FA_ID
     , LT_ID, PROD_ID, FL_ID, OP_ID, TIMEKEY, CHG_TM, CRT_TM
  FROM TEST02.TBL_LT_INF A
 WHERE NOT EXISTS (
                  SELECT 1
                    FROM TEST01.TBL_LT_INF IA
                   WHERE IA.FA_ID = A.FA_ID
                     AND IA.LT_ID = A.LT_ID
                     AND IA.PROD_ID = A.PROD_ID
                   )
;
