CREATE OR REPLACE PROCEDURE HG_PROC
IS
P_TABLES ALL_TAB_COLUMNS%ROWTYPE;
BEGIN

    FOR F IN (SELECT TABLE_NAME,COLUMN_NAME
        FROM ALL_TAB_COLUMNS
        WHERE OWNER = 'TEST01'
            AND COLUMN_NAME = 'FA_ID')
    LOOP
    EXECUTE IMMEDIATE 'INSERT INTO HOMEWK_01 SELECT :1,:2,FA_ID,COUNT(FA_ID) FROM '|| F.TABLE_NAME||' GROUP BY FA_ID' USING F.TABLE_NAME,'FA_ID';
    --DBMS_OUTPUT.PUT_LINE(F.TABLE_NAME||' '||F.COLUMN_NAME);
    END LOOP;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
END;
